[options]
addons_path = /mnt/extra-addons
db_host = db
db_port = 5432
db_user = admin
db_password = admin
admin_passwd = $pbkdf2-sha512$600000$MaaU0ppzbo3xXkupVSolhA$Toagnkl/HfnxbgOmotULwK0joYbboal/Ushiohm1xbhuE.VT3WUVL2Cxe4oo3TDnzhJRetM8JLaW5.qFyF1Bzg

