[options]
addons_path = /mnt/extra-addons
db_host = db
db_port = 5432
db_user = admin
db_password = admin
admin_passwd = $pbkdf2-sha512$600000$AOB8j/FeS8kZozTGuNdaSw$f.pHufqSZvLjOhDQou3TqcOSJYgZtMp7pTtTuMvv.c7sasWFuZOvfA/SpyAEbZaZ1zn1RTRDtB4iaaeFTlIDBg

