[options]
addons_path = /mnt/extra-addons
db_host = db
db_port = 5432
db_user = admin
db_password = admin
admin_passwd = $pbkdf2-sha512$600000$x3iP0Ton5JxzLoXwPofwHg$FhQhI9FW4WkFCrB7cku7mHLkZSnjrLeo/wGvcnLKsYS4Q.a3IUIDRjO/0y7xW4LvCBJOwZooS/W8qtByowOqdQ

